name: Generate manifest.json

on:
  push:
    branches: [ "main" ]
    paths:
      - "tools/**.user.js"
      - "build-manifest.js"
      - ".github/workflows/generate-manifest.yml"
      - "index.html"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build manifest.json
        run: node build-manifest.js

      - name: Commit & push manifest
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add manifest.json
            git commit -m "chore: update manifest.json"
            git push
          else
            echo "No changes."
          fi
